import fs from '\0polyfill-node.__fs/browserify-fs';

export var appendFile = fs.appendFile;
export var chmod = fs.chmod;
export var chown = fs.chown;
export var close = fs.close;
export var createReadStream = fs.createReadStream;
export var createWriteStream = fs.createWriteStream;
export var exists = fs.exists;
export var fchmod = fs.fchmod;
export var fchown = fs.fchown;
export var fstat = fs.fstat;
export var fsync = fs.fsync;
export var ftruncate = fs.ftruncate;
export var futimes = fs.futimes;
export var lchmod = fs.lchmod;
export var lchown = fs.lchown;
export var link = fs.link;
export var lstat = fs.lstat;
export var mkdir = fs.mkdir;
export var notify = fs.notify;
export var open = fs.open;
export var read = fs.read;
export var readFile = fs.readFile;
export var readdir = fs.readdir;
export var readlink = fs.readlink;
export var realpath = fs.realpath;
export var rename = fs.rename;
export var rmdir = fs.rmdir;
export var stat = fs.stat;
export var symlink = fs.symlink;
export var truncate = fs.truncate;
export var unlink = fs.unlink;
export var unwatchFile = fs.unwatchFile;
export var utimes = fs.utimes;
export var watch = fs.watch;
export var watchFile = fs.watchFile;
export var write = fs.write;
export var writeFile = fs.writeFile;

export default fs;
